<?php
return [
    'warehouse' => [
        'name' => 'Cửa hàng & Kho Goodwill Việt Nam',
        'address' => '328 Ngô Quyền, Mân Thái, Quận Sơn Trà, Đà Nẵng, Việt Nam',
        'city' => 'Đà Nẵng',
        'district' => 'Sơn Trà',
        'place_id' => null,
        // Fixed coordinates (absolute). Prefer setting via Google picker in admin/warehouse-location.php
        'lat' => 16.047079,
        'lng' => 108.206230,
    ],
    'relay_network' => [
        'northbound' => [
            [
                'code' => 'hue_center',
                'name' => 'Kho trung chuyển Huế',
                'address' => '20 Lý Thường Kiệt, Phú Nhuận, Huế, Việt Nam',
                'city' => 'Huế',
                'district' => 'Phú Nhuận',
                'lat' => 16.4637137,
                'lng' => 107.5908665,
            ],
            [
                'code' => 'dong_hoi_center',
                'name' => 'Kho trung chuyển Đồng Hới',
                'address' => '45 Quang Trung, Đồng Hải, Đồng Hới, Quảng Bình, Việt Nam',
                'city' => 'Đồng Hới',
                'district' => 'Đồng Hải',
                'lat' => 17.46885,
                'lng' => 106.62226,
            ],
            [
                'code' => 'vinh_center',
                'name' => 'Kho trung chuyển Vinh',
                'address' => '12 Lê Lợi, Hưng Bình, Vinh, Nghệ An, Việt Nam',
                'city' => 'Vinh',
                'district' => 'Hưng Bình',
                'lat' => 18.679584,
                'lng' => 105.681335,
            ],
            [
                'code' => 'ninh_binh_center',
                'name' => 'Kho trung chuyển Ninh Bình',
                'address' => '9 Tràng An, Đông Thành, Ninh Bình, Việt Nam',
                'city' => 'Ninh Bình',
                'district' => 'Đông Thành',
                'lat' => 20.250614,
                'lng' => 105.974453,
            ],
            [
                'code' => 'ha_noi_gateway',
                'name' => 'Kho trung chuyển Hà Nội',
                'address' => '55 Nguyễn Văn Cừ, Long Biên, Hà Nội, Việt Nam',
                'city' => 'Hà Nội',
                'district' => 'Long Biên',
                'lat' => 21.043094,
                'lng' => 105.874643,
            ],
        ],
        'southbound' => [
            [
                'code' => 'tam_ky_center',
                'name' => 'Kho trung chuyển Tam Kỳ',
                'address' => '8 Phan Châu Trinh, Phước Hòa, Tam Kỳ, Quảng Nam, Việt Nam',
                'city' => 'Tam Kỳ',
                'district' => 'Phước Hòa',
                'lat' => 15.573013,
                'lng' => 108.474591,
            ],
            [
                'code' => 'quang_ngai_center',
                'name' => 'Kho trung chuyển Quảng Ngãi',
                'address' => '105 Hùng Vương, Trần Phú, Quảng Ngãi, Việt Nam',
                'city' => 'Quảng Ngãi',
                'district' => 'Trần Phú',
                'lat' => 15.121387,
                'lng' => 108.804414,
            ],
            [
                'code' => 'quy_nhon_center',
                'name' => 'Kho trung chuyển Quy Nhơn',
                'address' => '33 Nguyễn Tất Thành, Lý Thường Kiệt, Quy Nhơn, Bình Định, Việt Nam',
                'city' => 'Quy Nhơn',
                'district' => 'Lý Thường Kiệt',
                'lat' => 13.782967,
                'lng' => 109.219663,
            ],
            [
                'code' => 'nha_trang_center',
                'name' => 'Kho trung chuyển Nha Trang',
                'address' => '18 Thái Nguyên, Phước Tân, Nha Trang, Khánh Hòa, Việt Nam',
                'city' => 'Nha Trang',
                'district' => 'Phước Tân',
                'lat' => 12.24507,
                'lng' => 109.19432,
            ],
            [
                'code' => 'bien_hoa_center',
                'name' => 'Kho trung chuyển Biên Hòa',
                'address' => '90 Võ Thị Sáu, Thống Nhất, Biên Hòa, Đồng Nai, Việt Nam',
                'city' => 'Biên Hòa',
                'district' => 'Thống Nhất',
                'lat' => 10.94469,
                'lng' => 106.82432,
            ],
            [
                'code' => 'hcm_gateway',
                'name' => 'Kho trung chuyển TP Hồ Chí Minh',
                'address' => '120 Điện Biên Phủ, Đa Kao, Quận 1, TP Hồ Chí Minh, Việt Nam',
                'city' => 'TP Hồ Chí Minh',
                'district' => 'Quận 1',
                'lat' => 10.787157,
                'lng' => 106.702522,
            ],
            [
                'code' => 'can_tho_gateway',
                'name' => 'Kho trung chuyển Cần Thơ',
                'address' => '2 Hòa Bình, Tân An, Ninh Kiều, Cần Thơ, Việt Nam',
                'city' => 'Cần Thơ',
                'district' => 'Ninh Kiều',
                'lat' => 10.03419,
                'lng' => 105.78717,
            ],
        ],
    ],
    'destination_warehouses' => [
        [
            'code' => 'son_tra_last_mile',
            'name' => 'Kho giao Sơn Trà',
            'address' => '328 Ngô Quyền, Mân Thái, Quận Sơn Trà, Đà Nẵng, Việt Nam',
            'city' => 'Đà Nẵng',
            'district' => 'Sơn Trà',
            'lat' => 16.047079,
            'lng' => 108.206230,
        ],
        [
            'code' => 'hai_chau_last_mile',
            'name' => 'Kho giao Hải Châu',
            'address' => '85 Lê Duẩn, Hải Châu, Đà Nẵng, Việt Nam',
            'city' => 'Đà Nẵng',
            'district' => 'Hải Châu',
            'lat' => 16.070266,
            'lng' => 108.220604,
        ],
        [
            'code' => 'thanh_khe_last_mile',
            'name' => 'Kho giao Thanh Khê',
            'address' => '271 Điện Biên Phủ, Thanh Khê, Đà Nẵng, Việt Nam',
            'city' => 'Đà Nẵng',
            'district' => 'Thanh Khê',
            'lat' => 16.067838,
            'lng' => 108.194167,
        ],
        [
            'code' => 'ha_noi_cau_giay',
            'name' => 'Kho giao Cầu Giấy',
            'address' => '129 Cầu Giấy, Quan Hoa, Cầu Giấy, Hà Nội, Việt Nam',
            'city' => 'Hà Nội',
            'district' => 'Cầu Giấy',
            'lat' => 21.033781,
            'lng' => 105.799446,
        ],
        [
            'code' => 'ha_noi_long_bien',
            'name' => 'Kho giao Long Biên',
            'address' => '55 Nguyễn Văn Cừ, Long Biên, Hà Nội, Việt Nam',
            'city' => 'Hà Nội',
            'district' => 'Long Biên',
            'lat' => 21.043094,
            'lng' => 105.874643,
        ],
        [
            'code' => 'hcm_quan1',
            'name' => 'Kho giao Quận 1',
            'address' => '120 Điện Biên Phủ, Đa Kao, Quận 1, TP Hồ Chí Minh, Việt Nam',
            'city' => 'TP Hồ Chí Minh',
            'district' => 'Quận 1',
            'lat' => 10.787157,
            'lng' => 106.702522,
        ],
        [
            'code' => 'hcm_thu_duc',
            'name' => 'Kho giao Thủ Đức',
            'address' => '34 Võ Văn Ngân, Bình Thọ, Thủ Đức, TP Hồ Chí Minh, Việt Nam',
            'city' => 'TP Hồ Chí Minh',
            'district' => 'Thủ Đức',
            'lat' => 10.850549,
            'lng' => 106.755425,
        ],
        [
            'code' => 'can_tho_ninh_kieu',
            'name' => 'Kho giao Ninh Kiều',
            'address' => '2 Hòa Bình, Tân An, Ninh Kiều, Cần Thơ, Việt Nam',
            'city' => 'Cần Thơ',
            'district' => 'Ninh Kiều',
            'lat' => 10.03419,
            'lng' => 105.78717,
        ],
        [
            'code' => 'hai_phong_ngo_quyen',
            'name' => 'Kho giao Ngô Quyền',
            'address' => '48 Lạch Tray, Ngô Quyền, Hải Phòng, Việt Nam',
            'city' => 'Hải Phòng',
            'district' => 'Ngô Quyền',
            'lat' => 20.852571,
            'lng' => 106.688087,
        ],
    ],
    'simulation' => [
        'auto_deliver_enabled' => true,
        'auto_deliver_min_seconds' => 30,
        // Seconds needed to move from one relay hub to the next (tracking simulation)
        'transit_seconds_per_hub' => 180,
    ],
];
